name: Build and Publish Availability Dashboard

on:
  workflow_dispatch:
  schedule:
    - cron: "10 11 * * 1-5"  # Weekdays 11:10 UTC (~7:10 AM ET)

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Install Playwright (no package.json needed)
      - name: Install Playwright package
        run: npm i playwright@1.47.0 --no-save

      # Cache Chromium binaries to speed up subsequent runs
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: pw-${{ runner.os }}-v1
          restore-keys: |
            pw-${{ runner.os }}-

      - name: Install Chromium browser
        run: npx playwright install chromium

      # Prepare the site first with a fallback JSON to avoid 404 on the very first load
      - name: Prepare static site (with fallback)
        run: |
          mkdir -p site
          cp web/index.html site/index.html
          echo "[]" > site/availability.json

      # Run checker; if it succeeds, overwrite fallback JSON
      - name: Run ChiliPiper check
        run: |
          node check-availability.cjs
          if [ -f "availability.json" ]; then cp availability.json site/availability.json; fi

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
